development:
  adapter: postgresql
  encoding: unicode
  database: ddg_development
  pool: 5
  username: ddg
  password: dedege

test:
  adapter: postgresql
  encoding: unicode
  database: ddg_test
  pool: 5
  username: ddg
  password: dedege
  
production:
  adapter: postgresql
  encoding: unicode
  database: ddg_production
  pool: 5
  username: ddg
  password: dedege
